/**
 * Protocol-level error codes used in `err` messages sent from server to client.
 */
export const ErrorCodes = {
  COLLECTION_NOT_REGISTERED: 'COLLECTION_NOT_REGISTERED',
  INVALID_MESSAGE: 'INVALID_MESSAGE',
  DOCUMENT_NOT_FOUND: 'DOCUMENT_NOT_FOUND',
  CONNECTION_CLOSED: 'CONNECTION_CLOSED',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  SERVER_ERROR: 'SERVER_ERROR',
  UNSUPPORTED_PROTOCOL_VERSION: 'UNSUPPORTED_PROTOCOL_VERSION',
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  AUTH_FAILED: 'AUTH_FAILED',
  SUBSCRIPTION_LIMIT_EXCEEDED: 'SUBSCRIPTION_LIMIT_EXCEEDED',
  CONNECTION_LIMIT_EXCEEDED: 'CONNECTION_LIMIT_EXCEEDED',
} as const;

export type RealtimeErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
